/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          help: "",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text1843675174",
          max: 0,
          min: 0,
          name: "description",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          help: "",
          hidden: false,
          id: "number674557499",
          max: null,
          min: null,
          name: "totalPrice",
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: "number",
        },
        {
          help: "",
          hidden: false,
          id: "select2063623452",
          maxSelect: 0,
          name: "status",
          presentable: false,
          required: true,
          system: false,
          type: "select",
          values: [
            "draft",
            "ordered",
            "inTransit",
            "delivered",
            "archived",
            "returned",
          ],
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text4283914359",
          max: 0,
          min: 0,
          name: "store",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          exceptDomains: null,
          help: "",
          hidden: false,
          id: "url669363014",
          name: "orderUrl",
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: "url",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text2809179246",
          max: 0,
          min: 0,
          name: "externalId",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text3711727087",
          max: 0,
          min: 0,
          name: "trackingCode",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          help: "",
          hidden: false,
          id: "date1611150777",
          max: "",
          min: "",
          name: "deliveredAt",
          presentable: false,
          required: false,
          system: false,
          type: "date",
        },
        {
          help: "",
          hidden: false,
          id: "date1099083232",
          max: "",
          min: "",
          name: "archivedAt",
          presentable: false,
          required: false,
          system: false,
          type: "date",
        },
        {
          cascadeDelete: false,
          collectionId: "pbc_1219621782",
          help: "",
          hidden: false,
          id: "relation1874629670",
          maxSelect: 10,
          minSelect: 0,
          name: "tags",
          presentable: false,
          required: false,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_3527180448",
      indexes: [],
      listRule: null,
      name: "orders",
      system: false,
      type: "base",
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_3527180448");

    return app.delete(collection);
  },
);
